### ISSUE TITLE
aplikasi force close

### ISSUE THREAD

**Issue by lulungsatrioprayuda** [lulungsatrioprayuda/image_processing_trial#1]
flutter aplikasi saya memiliki bug dimana disaat saya ingin klik salah satu gambar dari gallery atau ingin mengambil gambar dari kamera secara  langsung aplikasi pun otomatis force close , bug ini sebelumnya tak terjadi sebelum saya membuat function untuk men load model tflite pada flutter tersebut, dan bug ada pada file lib/pages/home.dart,

**Comment by lulungsatrioprayuda** [comment]
ini error yang ada di debug console nya
I/tflite  (11948): Initialized TensorFlow Lite runtime.
2
W/System  (11948): A resource failed to call close.
I/rocessing_tria(11948): ProcessProfilingInfo new_methods=630 is saved saved_to_disk=1 resolve_classes_delay=8000
V/MiuiFrameworkFactory(11948): get AllImpl object = android.common.MiuiFrameworkFactoryImpl@9b330ce
W/MirrorManager(11948): this model don't Support
I/Timeline(11948): Timeline: Activity_launch_request time:1710387888
D/SurfaceView(11948): UPDATE Surface(name=SurfaceView - com.example.image_processing_trial/com.example.image_processing_trial.MainActivity)/@0x87c39e7, mIsProjectionMode = false
I/Timeline(11948): Timeline: Activity_launch_request time:1710393913
D/SurfaceView(11948): UPDATE Surface(name=SurfaceView - com.example.image_processing_trial/com.example.image_processing_trial.MainActivity)/@0xce595e2, mIsProjectionMode = false
E/libc    (11948): Access denied finding property "ro.hardware.chipname"
E/AndroidRuntime(11948): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime(11948): Process: com.example.image_processing_trial, PID: 11948
E/AndroidRuntime(11948): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(11948): 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
E/AndroidRuntime(11948): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(11948): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(11948): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(11948): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
E/AndroidRuntime(11948): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(11948): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(11948): 	at java.lang.Thread.run(Thread.java:923)
E/AndroidRuntime(11948): Caused by: java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite tensor with type UINT8 and a Java object of type [[F (which is compatible with the TensorFlowLite type FLOAT32).
E/AndroidRuntime(11948): 	at org.tensorflow.lite.TensorImpl.throwIfTypeIsIncompatible(TensorImpl.java:401)
E/AndroidRuntime(11948): 	at org.tensorflow.lite.TensorImpl.copyTo(TensorImpl.java:214)
E/AndroidRuntime(11948): 	at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:255)

**Comment by lulungsatrioprayuda** [comment]
![image](https://user-images.githubusercontent.com/55550472/158980513-ab09af30-ae88-41e0-b32c-ba23fc8d3ec4.png)

**Comment by luthfidhani** [comment]
kayanya masalahnya ini
`E/libc (11948): Access denied finding property "ro.hardware.chipname"`

**Comment by lulungsatrioprayuda** [comment]
nemu issue yang sama cuma beliau os platformnya linux
https://github.com/tensorflow/tensorflow/issues/52914
